
name: Minecraft Server Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # runs every 6 hours

jobs:
  run-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Accept EULA
        run: echo "eula=true" > server/eula.txt

- name: Install Playit Tunnel
  run: |
    curl -L https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64 -o playit
    chmod +x playit
    ./playit & sleep 5


      - name: Run Minecraft server
        run: |
          cd server
          java -Xmx1G -Xms1G -jar server.jar nogui
